[build]
  base = "."
  command = "npm run build"
  publish = "dist/public"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/ws/*"
  to = "/.netlify/functions/websocket/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200